---
# tasks file for httpd
- name: Install Apache HTTP server
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes

- name: Copy index.html to web root
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
